version: '3.8'
services:
  ### Eureka Server
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_ENABLESELF_PRESERVATION=false
      - EUREKA_SERVER_WAITTIMEINMS_WHEN_SYNC_EMPTY=0

  ### PostgreSQL database for Cars
  db-car-inventory:
    container_name: db-car-inventory
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: car_inventory_db
      POSTGRES_USER: tiendaCars
      POSTGRES_PASSWORD: Test123
    ports:
      - "5431:5432"
    expose:
      - "5432"

  ### PostgreSQL database for Booking
  db-booking:
    container_name: db-booking
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: tiendaCars
      POSTGRES_PASSWORD: Test123
    ports:
      - "5435:5432"
    expose:
      - "5435"

  ### PostgreSQL database for Payments
  db-payments:
    container_name: db-payments
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: tiendaCars
      POSTGRES_PASSWORD: Test123
    ports:
      - "5433:5432"
    expose:
      - "5432"

  ### Cars Service
  cars-service:
    build:
      context: ./cars-service
    container_name: cars-service
    ports:
      - "8081:8081"
    depends_on:
      - db-car-inventory
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-car-inventory:5432/car_inventory_db
      SPRING_DATASOURCE_USERNAME: tiendaCars
      SPRING_DATASOURCE_PASSWORD: Test123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  ### Booking Service
  booking-service:
    build:
      context: ./booking-service
    container_name: booking-service
    ports:
      - "8083:8083"
    depends_on:
      - db-booking
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-booking:5432/booking_db
      SPRING_DATASOURCE_USERNAME: tiendaCars
      SPRING_DATASOURCE_PASSWORD: Test123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  ### Payment Service
  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - db-payments
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-payments:5432/payments_db
      SPRING_DATASOURCE_USERNAME: tiendaCars
      SPRING_DATASOURCE_PASSWORD: Test123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  ### Zipkin for Distributed Tracing
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:latest
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
