server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.h2.Driver
    dbcp2:
      username: sa
      password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  hystrix:
    enable:true

